-- ViewCount đã có (patch thủ công trước đó) → đánh dấu migration đã apply
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260702061459_AddViewCountToResearchPaper', '9.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260702061459_AddViewCountToResearchPaper'
);

-- AddPaperPdfFile: PendingPapers đã có PdfUrl, chỉ thêm cột còn thiếu
ALTER TABLE "PendingPapers" ADD COLUMN IF NOT EXISTS "PdfAccessType" character varying(50);
ALTER TABLE "PendingPapers" ADD COLUMN IF NOT EXISTS "PdfLicense" character varying(100);

CREATE TABLE IF NOT EXISTS "PaperPdfFiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ResearchPaperId" integer NOT NULL,
    "ExternalSource" character varying(100) NOT NULL,
    "SourceUrl" character varying(1000) NOT NULL,
    "LocalRelativePath" character varying(500) NOT NULL,
    "SizeBytes" bigint,
    "ContentType" character varying(100),
    "Sha256" character varying(64),
    "Status" character varying(50) NOT NULL,
    "FailureReason" character varying(1000),
    "EnqueuedAt" timestamp without time zone NOT NULL,
    "CompletedAt" timestamp without time zone,
    "AttemptCount" integer NOT NULL,
    CONSTRAINT "PK_PaperPdfFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaperPdfFiles_ResearchPapers_ResearchPaperId"
        FOREIGN KEY ("ResearchPaperId") REFERENCES "ResearchPapers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PaperPdfFiles_ResearchPaperId" ON "PaperPdfFiles" ("ResearchPaperId");
CREATE INDEX IF NOT EXISTS "IX_PaperPdfFiles_Status" ON "PaperPdfFiles" ("Status");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260708174319_AddPaperPdfFile', '9.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260708174319_AddPaperPdfFile'
);
